import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.models.scan import Scan


def generate_scan_pdf(scan: Scan) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=20, textColor=colors.HexColor("#10B981"))
    body = styles["Normal"]
    elements: list = []

    elements.append(Paragraph("VulnLens Security Report", title_style))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"<b>Project:</b> {scan.project_name}", body))
    elements.append(Paragraph(f"<b>Scan Type:</b> {scan.scan_type}", body))
    elements.append(Paragraph(f"<b>Score:</b> {scan.score} — Risk: {scan.risk_level}", body))
    elements.append(Paragraph(f"<b>Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body))
    elements.append(Spacer(1, 16))

    elements.append(
        Paragraph(
            "<b>DISCLAIMER:</b> This report is generated by automated static/passive analysis only. "
            "It does not constitute a penetration test or guarantee of security. "
            "Findings may include false positives. Validate all issues manually before remediation.",
            ParagraphStyle("Disclaimer", parent=body, fontSize=9, textColor=colors.grey),
        )
    )
    elements.append(Spacer(1, 20))

    if not scan.issues:
        elements.append(Paragraph("No issues detected.", body))
    else:
        elements.append(Paragraph(f"<b>Findings ({len(scan.issues)})</b>", styles["Heading2"]))
        elements.append(Spacer(1, 8))
        for idx, issue in enumerate(scan.issues, 1):
            elements.append(Paragraph(f"{idx}. [{issue.severity}] {issue.title}", styles["Heading3"]))
            elements.append(Paragraph(issue.description, body))
            elements.append(Paragraph(f"<i>Risk:</i> {issue.risk_explanation}", body))
            if issue.evidence:
                elements.append(Paragraph(f"<i>Evidence:</i> <font face='Courier' size='8'>{issue.evidence[:300]}</font>", body))
            elements.append(Paragraph(f"<b>Recommendation:</b> {issue.recommendation}", body))
            if issue.developer_friendly_summary:
                elements.append(
                    Paragraph(
                        f"<b>Developer summary:</b> {issue.developer_friendly_summary}",
                        body,
                    )
                )
            if issue.ai_enhanced:
                elements.append(
                    Paragraph(
                        "<i>Enhanced by Groq AI — validate recommendations manually.</i>",
                        ParagraphStyle("AI", parent=body, fontSize=9, textColor=colors.HexColor("#10B981")),
                    )
                )
            if issue.secure_example:
                elements.append(
                    Paragraph(
                        f"<b>Secure example:</b> <font face='Courier' size='8'>{issue.secure_example[:400]}</font>",
                        body,
                    )
                )
            elements.append(Spacer(1, 10))

        # Summary table
        sev_counts: dict[str, int] = {}
        for issue in scan.issues:
            sev_counts[issue.severity] = sev_counts.get(issue.severity, 0) + 1
        table_data = [["Severity", "Count"]] + [[k, str(v)] for k, v in sorted(sev_counts.items())]
        t = Table(table_data, colWidths=[2 * inch, 1 * inch])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )
        elements.append(Spacer(1, 12))
        elements.append(t)

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
